server:
  port: 8081

debug: true

spring:
  http:
    multipart:
      max-request-size: 10Mb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.109.183:3306/test?characterEncoding=utf-8
    username: badguy
    password: 123456


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: cn.badguy.dream.pojo







